name: Go CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24.2"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Install OpenGL and GLFW dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libglfw3-dev \
            libx11-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxrandr-dev \
            libx11-xcb-dev

      - name: Install dependencies
        run: go mod tidy

      - name: Run golangci-lint
        run: golangci-lint run -c ./config/linter.yml --timeout=5m

      - name: Run tests
        run: go test ./...
