name: Go CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24.2"

      - name: Run golangci-lint
        uses: actions/golangci-lint@v2

      - name: Install OpenGL and GLFW dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgl1-mesa-dev \
            libglfw3-dev \
            libx11-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxrandr-dev \
            libx11-xcb-dev \
            curl
          curl -sSfL https://golangci-lint.run/install.sh | sh -s v2.10.1

      - name: Install dependencies
        run: go mod tidy

      - name: Run golang-ci
        run: golangci-lint run config ./config/linter.yml

      - name: Run tests
        run: go test ./...
